[kinematics]
type = "core_xy" # Different types of kinematics types are supported

max_velocity = "500 mm/s"
max_accel = "20000 mm/s^2"
max_z_velocity = "50 mm/s"
max_z_accel = "1200 mm/s^2"
x_range=["0","256 mm"]
y_range=["0","256 mm"]
z_range=["0","256 mm"]
square_corner_velocity="9.0 mm/s"

# What MCUs hold what axes
axis_x = ["mainboard", "stepper_x"]
axis_y = ["mainboard", "stepper_y"]
axis_z = ["mainboard", "stepper_z"]
axis_extruder = ["toolhead", "stepper_extruder"]

[mcu.mainboard]
type = "klipper"
connection = { type = "rpmsg", channel_name = "cpu_dsp0" }

[mcu.toolhead]
type = "klipper"

start_delay = "500 ms" # Wait for the printer to start after power on

connection_wrapper = {
    type = "elegoo_a55a",
    pin = "PE17"
}

connection = {
    type = "serial",
    path = "/dev/ttyS3",
    baud = 250000,
    timeout = "100 ms"
}

[axis]
stepper_x = { type = "dummy" }
stepper_y = { type = "dummy" }
stepper_z = { type = "dummy" }

stepper_extruder = { type = "dummy" }
